### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Mr-Clever1** [Vitzual/Vectorio#106]
Hey man, new to your game, absolutely amazing, recently unlocked research and I noticed you had a few typos, in the combat laser upgrade you missed the L in laser in one sentence, and you missed another L in lowering in collector storage 1,
I've come to notice there are quite a lot of Ls missing there may be something wrong with your L key
Thanks love your game

**Comment by Vitzual** [comment]
I've moved this to the project to-do list as a bug. Thanks for the heads up.
