### ISSUE TITLE
Stuck in delete mode on startup

### ISSUE THREAD

**Issue by SuperAndiChan** [Vitzual/Vectorio#107]
Sometimes when I load a world, the game thinks I’m holding right-click and starts deleting everything I move my mouse over. Most of the time when this happens in other games, I’d just press rmb to reset the input for it, but it doesn’t work for this issue and I have to exit and restart the game. It’s kind of annoying since I accidentally deleted a bunch of my research labs and a reactor so a fix would be very appreciated. Thanks!

**Comment by blockrock44** [comment]
Were you potentially holding alt down? You might try pressing that and seeing if the issue ceases, as there is an issue with how unity works that makes alt delete structures.
