### ISSUE TITLE
Gold exceed the max

### ISSUE THREAD

**Issue by Staco78** [Vitzual/Vectorio#110]
![image](https://user-images.githubusercontent.com/59371333/134078419-50b508de-8873-41b2-bc4f-51eea72f678f.png)

The gold increase to 731500 but the max is 209000 and stop increase at this value.

Version: Steam update 2
Windows 10

**Comment by blockrock44** [comment]
Did you try reloading the game? That is usually just an issue people have after researching more gold storage, so the displayed capacity is just wrong in that case.

**Comment by Staco78** [comment]
Yeah it's working after restart. But it's still remain a visual bug.
