### ISSUE TITLE
EA v0.3.0 Enabling and disabling research has a permanant effect on power/heat until relogged.

### ISSUE THREAD

**Issue by Noitabara** [Vitzual/Vectorio#117]
Experienced in Early Access v0.3.0
https://user-images.githubusercontent.com/5560528/145841303-f6ce4610-758a-47a7-9519-c7e25a9dc9c4.mp4

Unsure if videos work but the video displays the behavior- either way, steps to reproduce:
1. Place reactor
2. Enable a research, disable a research repeatedly
3. Results in a decrease of power/heat

**Comment by Vitzual** [comment]
This is now fixed on my end and will be out in v0.3.2

Thanks for the report!
