### ISSUE TITLE
Add main menu

### ISSUE THREAD

**Issue by Vitzual** [Vitzual/Vectorio#22]
- [x] Will have defenses and enemies in the background constantly fighting
- [x] Add options menu and clean interface
- [x] Add main menu music https://www.youtube.com/watch?v=73Jrq1sk8Y4&list=RD73Jrq1sk8Y4&index=1&ab_channel=LuigiDonatello

**Comment by bonn2** [comment]
Added in 75e940033b378661501852a746c4affecf3afaa3
