### ISSUE TITLE
Support Ultrawide Resolutions

### ISSUE THREAD

**Issue by betam4x** [Vitzual/Vectorio#64]
Many people have utrawide monitors that are 3440x1440 or 5120x1440 (or others). It would be great if you could support these resolutions.

**Comment by Vitzual** [comment]
I'll add this as part of the core refactor. Thanks.

~ Ben

**Comment by bonn2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for ultrawide resolutions](https://trello.com/c/iyQqpbOp/129-add-support-for-ultrawide-resolutions)
