### ISSUE TITLE
QOL: Multiselect

### ISSUE THREAD

**Issue by 7aman4013** [Vitzual/Vectorio#65]
It would be pretty nice to be able to multiselect buildings.

E.g. Select multiple ports at the same time to have them switch between building, eco, fixing, and combat

**Comment by bonn2** [comment]
Added to the trello board: [https://trello.com/b/BfiySKBr/vectorio](https://trello.com/b/BfiySKBr/vectorio)

**Comment by bonn2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Building Multiselect](https://trello.com/c/FYIQwYED/145-building-multiselect)
