### ISSUE TITLE
QOL: Autosave option

### ISSUE THREAD

**Issue by 7aman4013** [Vitzual/Vectorio#66]
The ability to disable autosaving in settings.

**Comment by bonn2** [comment]
Added to the trello board: [https://trello.com/b/BfiySKBr/vectorio](https://trello.com/b/BfiySKBr/vectorio)

**Comment by bonn2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Autosave toggle](https://trello.com/c/I7EMdueD/146-autosave-toggle)
