### ISSUE TITLE
QOL: Research Completion Notification

### ISSUE THREAD

**Issue by 7aman4013** [Vitzual/Vectorio#67]

**Comment by bonn2** [comment]
Added to the trello board: [https://trello.com/b/BfiySKBr/vectorio](https://trello.com/b/BfiySKBr/vectorio)

**Comment by bonn2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Research complete notification](https://trello.com/c/sqPd0d2E/147-research-complete-notification)
