### ISSUE TITLE
Incomplete Research Reset

### ISSUE THREAD

**Issue by YLopesCesari** [Vitzual/Vectorio#68]
I hope that's not a feature.
When you change your research to something else, then change back to it, sometimes it restarts from 0. When i was playing, that happened like 15 out of 20 times or something like that.

**Comment by bonn2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unfinished research not saving](https://trello.com/c/r9FAwDo8/148-unfinished-research-not-saving)
