### ISSUE TITLE
Negative Heat??

### ISSUE THREAD

**Issue by YLopesCesari** [Vitzual/Vectorio#69]
After reaching the 80000's, I sold almost everything except my (I don't remember the name{2nd tier anti-heat tower}) and the heat went to negative. Is that normal? All enemies stopped spawning. Maybe add some enemies that appear in negative heat.

Issue: Not really an issue, but Negative Heat? I think you guys should change to Cold on negatives, and maybe add some new enemies that spawn at negative heat.

**Comment by bonn2** [comment]
Do you have any area-coolers / area-freezers?

**Comment by YLopesCesari** [comment]
yeah, tons

**Comment by bonn2** [comment]
Then this is known, and until recently was in debate to be a feature or not. After the core refactor this feature will be patched out

**Comment by YLopesCesari** [comment]
I see, case closed then?

**Comment by bonn2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Area Freezers/Coolers allow negative heat](https://trello.com/c/Ws15u4S7/149-area-freezers-coolers-allow-negative-heat)

**Comment by bonn2** [comment]
Yes, but this issue will remain open until it is patched

**Comment by ltmauve** [comment]
When you say that the feature will be patched out, do you mean that there will no longer be area cooler/freezers, that they will work differently so negative heat is no longer possible to achieve, or that the interface will just no longer display how much heat you need to start enemy spawning again?

**Comment by bonn2** [comment]
Coolers will be changed to only cool nearby buildings by a percentage, thus making negative heat mathematically impossible

**Comment by SpookyHiya** [comment]
i personnaly think that they should stay the same
