### ISSUE TITLE
When that 400k tower CAN'T AIM AND THEN DIES

### ISSUE THREAD

**Issue by YLopesCesari** [Vitzual/Vectorio#71]
Turrets and other defenses miss shots very often when the enemy isn't going their way. It's annoying tbh :/

I had a whole set of rippers. Today I saw 17 of them shooting at the AIR and then like three of them got hit by a "saw" enemy (80k heat) and they LITERALLY DIED.

**Comment by Vitzual** [comment]
This is being incorporated as part of the core refactor.
