### ISSUE TITLE
There should be a way to see actual buffs research gives

### ISSUE THREAD

**Issue by Bolar-P** [Vitzual/Vectorio#74]
Completing some research upgrades gives bonus stats to some towers like bonus damage/attack speed for defenses and faster ore production for collectors and capacity for storage. It would be nice to see actual changes on building via some stat info/panel after selecting such a building on the map. In the economic part of upgrades, it is easy to see changes because numbers are shown after collector drones drop everything at storage, but with defenses, there is no such indicator. It is hard to feel changes to range, attack speed, damage, or piercing in the late game. This little information would give more satisfaction after finishing long research.

**Comment by Vitzual** [comment]
This has been added in Update 3.
