### ISSUE TITLE
License not usable by non-copyright holders

### ISSUE THREAD

**Issue by adri326** [Vitzual/Vectorio#75]
The GPLv3 license distributed with this project cannot be used by non-copyright holders, because the project depends on non-GPL libraries.

To my understanding, this means that any derivative work (fork, PR, patch, etc.) that did not remove these dependencies is a copyright infringement (removing the dependencies might also be a copyright infringement, but I am unsure of that).

I would recommend switching to a license that allows you to depend and link the software with non-GPL libraries, like `MIT`, `BSD` or `LGPLv3`.

**Comment by Vitzual** [comment]
Hello,

I did some reading up on GPLv3 and I believe your right, so for now I've removed the license. I've talked with the developers of one of the assets however and they said even with an MIT license that I couldn't include the dependencies. So I'll be looking over a few different licenses and seeing which one best suits our situation. 

(And yes, I do realize this means no one can use the project without explicit permission from me first for the time being.)

Thanks,
Ben
