### ISSUE TITLE
Alt key deletes objects, Alt+Tab leads to accidentally deleting things

### ISSUE THREAD

**Issue by NathanS48** [Vitzual/Vectorio#80]
This is a request to simply remove the fact that the alt key deletes objects that your mouse is hovering over. I keep accidentally deleting things when I alt tab. If you want to keep this function, perhaps allow a way to disable it if a player wishes to?

**Comment by blockrock44** [comment]
I believe Vitzual plans on adding the ability to change key-binds eventually. I understand the frustration though, so it is unfortunate that this is currently how it works.

**Comment by Vitzual** [comment]
This is an issue with how Unity handles input my default. It's already been fixed as part of the refactor.
