### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Robozimal** [Vitzual/Vectorio#81]
Hi :D 

I think it would be cool to add a translation to the game so that people that speak other languages than english can play the game easier.
I myself could help translating to spanish (Español de España)
Also in a future, achivements should be considered and if they are added you can always reach to me at any time to translate them to spanish :D

**Comment by Vitzual** [comment]
Thanks for the interest! I am still trying to find a good system where the community can collaborate on translating the game to other languages, but I don't want to setup anything until I'm totally sure on what will actually need to be translated. I would hate for people to spend time translating portions of the game, only to then have it be removed later!

**Comment by Robozimal** [comment]
I agree, if you need help with anything I´ll be happy to help :D 
And (in the future) when you want help with the translation i´ll be happy to help :D
