### ISSUE TITLE
Logical transportation 

### ISSUE THREAD

**Issue by 83ben38** [Vitzual/Vectorio#82]
Because resource drones are needed to transport from resource nodes to storages, it would be logical to transport resources to and from builder drones (when selling and building) and research labs. Also, selling buildings should not be instant and should have a process similar to building.

**Comment by Vitzual** [comment]
Although this makes sense, that would slow down the building process too much. Having drones act as a bottleneck to how quickly you can build is about as far as I want to take it.

With that said, the idea of long range transportation freighters is still on my radar. So then having a transport drone be able to move resources from a storage to a train may be a good idea.

**Comment by 83ben38** [comment]
so, what about selling buildings in a similar manner to building?
