### ISSUE TITLE
Feature request: Visually indicate how much gold is in a gold collector?

### ISSUE THREAD

**Issue by werner291** [Vitzual/Vectorio#83]
Hello,

I think it would be useful if gold collectors somehow indicated how much gold was in them, to give some kind of visual indication of whether I need to build more drone ports.

**Comment by Vitzual** [comment]
This is planned as part of Update 3. Collectors will have a light on them, indicating one of three states - Collecting (Green), Full (Red), and Overclocked (Blue). The overclocked indicator will also give more of an indication when placing enhancers.
