### ISSUE TITLE
Turrets keep firing after enemy has left the board

### ISSUE THREAD

**Issue by nighthawkcmp** [Vitzual/Vectorio#86]
I recently found a bug where once the orange arrow shaped enemies left the area, my turrets kept firing (and missing) at it, and wouldnt retarget. if it happens again ill screenshot it and attach it here.

**Comment by nighthawkcmp** [comment]
got a screenshot of my artillary firing at nothing after an enemy left the area
 ![image](https://user-images.githubusercontent.com/89346218/130357724-db5840da-d9a9-4050-8134-44b5735c9dde.png)

**Comment by Vitzual** [comment]
This is a known issue and has been fixed in the refactor. 

Will leave this issue open until the refactor is out in case anyone else has the same issue.
