### ISSUE TITLE
Negative Heat Issue

### ISSUE THREAD

**Issue by vietnameserice** [Vitzual/Vectorio#87]
If you go into a negative heat (IDK exactly how low but -4000 is when this glitch happened) and save then relaunch the game it just glitches out and it changes the border (check picture) and is irreversible afterwards and you have to make a new game.

![image_2021-08-25_211313](https://user-images.githubusercontent.com/89564876/130899470-ec0a4b2d-8fd4-4dbd-8b01-189f9955102a.png)

Hope this gets resolved soon!

**Comment by notMEEPoffaith** [comment]
hm yello thats interersting
